# Makefile generic - Sources

#
# Builds the list of source files and object files for each bynary type.
#

# For the dynamic library/shared object.
TEMP = $(wildcard $(SRCDIR)/*$(SRCSUF))
ifeq ($(strip $(TEMP)),)
$(error ERROR: No source code found at $(SRCDIR)/*$(SRCSUF) )
endif
FILES = $(TEMP)
OBJS = $(addprefix $(OBJDIR)/,$(addsuffix $(OBJSUF), $(basename $(notdir $(FILES) ) ) ) )

# For the examples.
TEM2 = $(wildcard $(EXMDIR)/*.dpr)
ifeq ($(strip $(TEM2)),)
$(error ERROR: No source code found at $(EXMDIR)/*.dpr)
endif
EXMFILES = $(addprefix $(EXMDIR)/,$(addsuffix $(BINSUF), $(basename $(notdir $(TEM2) ) ) ) )

# For the demo game.
TEM3 = $(wildcard $(DEMODIR)/*.pas)
ifeq ($(strip $(TEM3)),)
$(error ERROR: No source code found at $(DEMODIR)/*)
endif
TEM4 = $(wildcard $(DEMODIR)/*.dpr)
ifeq ($(strip $(TEM4)),)
$(error ERROR: No source code found at $(DEMODIR)/*)
endif
DEMOSRC = $(DEMODIR)/%.dpr $(TEM3)
DEMO = $(addprefix $(DEMODIR)/,$(addsuffix $(BINSUF), $(basename $(notdir $(TEM4) ) ) ) )

