# Makefile generic - Sources

#
# Builds the list of source files and object files for each bynary type.
#

# Allegro sources
LIBFILES = $(wildcard $(LIBSRC)*$(LIBSUF))
ifeq ($(strip $(LIBFILES)),)
$(error ERROR: No source code found at $(LIBSRC))
endif

# For the examples.
TEXM = $(wildcard $(EXMSRC)ex_*$(MAINSUF))
ifeq ($(strip $(TEXM)),)
$(error ERROR: No source code found at $(EXMSRC))
endif
EXMFILES = $(addprefix $(EXMBIN),$(addsuffix $(BINSUF), $(basename $(notdir $(TEXM) ) ) ) )

# For the demonstration games.
TDEMfp = $(wildcard) $(FPSRC)*.pas
ifeq ($(strip $(TDEMfp)),)
$(error ERROR: No source code for demonstration game Furious Paladin
endif
FURIOUSPALADIN = $(FPBIN)furiouspaladin$(BINSUF)

TDEMpa = $(wildcard) $(PASRC)*.pas
ifeq ($(strip $(TDEMpa)),)
$(error ERROR: No source code for demonstration game Pascaleroids
endif
PASCALEROIDS =  $(PABIN)pascaleroids$(BINSUF)

DEMFILES = $(FURIOUSPALADIN) $(PASCALEROIDS)

# Documentation files
DOCMAIN = $(DOCSRC)allegro5.pds
DOCINTRO = $(DOCSRC)introduction.pds
DOCFILES  = $(DOCMAIN) $(DOCINTRO) $(DOCFINAL)

# Object files et all.

ALLFILES = $(LIBFILES) $(TEXM) $(TDEMfp)

DOCTMPFILES = $(addprefix $(OBJDIR), $(addsuffix .pduc, $(basename $(notdir $(LIBFILES) ) ) ) )

OBJFILES = $(addprefix $(OBJDIR), $(addsuffix .o, $(basename $(notdir $(ALLFILES) ) ) ) )
OBJFILES += $(addprefix $(OBJDIR), $(addsuffix .ppu, $(basename $(notdir $(ALLFILES) ) ) ) )
OBJFILES += $(addprefix $(OBJDIR), $(addsuffix .a, $(basename $(notdir $(ALLFILES) ) ) ) )

