
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


  { Allegro datafile object indexes, produced by grabber v4.4.2, Unix  }
  { Datafile: /home/guillermo/prog/bibliotecas/allegro-pas/allegro.pas.TRUNK/demo/demo.dat  }
  { Date: Wed Dec  5 19:35:52 2012  }
  { Do not hand edit!  }
  { BMP   }

  const
    BMP_COIN = 0;    
  { BMP   }
    BMP_BLK1 = 1;    
  { BMP   }
    BMP_BLK2 = 2;    
  { BMP   }
    BMP_BLK3 = 3;    
  { RLE   }
    BMP_BOMB1 = 4;    
  { RLE   }
    BMP_BOMB2 = 5;    
  { RLE   }
    BMP_EXPLOSION1 = 6;    
  { RLE   }
    BMP_EXPLOSION2 = 7;    
  { RLE   }
    BMP_MAIN_L0 = 8;    
  { RLE   }
    BMP_MAIN_L1 = 9;    
  { RLE   }
    BMP_MAIN_L2 = 10;    
  { RLE   }
    BMP_MAIN_L3 = 11;    
  { RLE   }
    BMP_MAIN_LD = 12;    
  { RLE   }
    BMP_MAIN_LJ = 13;    
  { RLE   }
    BMP_MAIN_R0 = 14;    
  { RLE   }
    BMP_MAIN_R1 = 15;    
  { RLE   }
    BMP_MAIN_R2 = 16;    
  { RLE   }
    BMP_MAIN_R3 = 17;    
  { RLE   }
    BMP_MAIN_RD = 18;    
  { RLE   }
    BMP_MAIN_RJ = 19;    
  { FONT  }
    GAME_FONT = 20;    
  { SAMP  }
    GAME_MUSIC = 21;    
  { PAL   }
    GAME_PAL = 22;    
  { FLIC  }
    INTRO_ANIM = 23;    
  { MIDI  }
    INTRO_MUSIC = 24;    
  { SAMP  }
    INTRO_SPL = 25;    
  { SAMP  }
    SND_COIN = 26;    
  { SAMP  }
    SND_DEAD = 27;    
  { SAMP  }
    SND_EXPLODE = 28;    
  { SAMP  }
    SND_JUMP = 29;    
  { SAMP  }
    SND_WIN = 30;    
  { BMP   }
    TITLE_BMP = 31;    
  { FONT  }
    TITLE_FONT = 32;    
  { MIDI  }
    TITLE_MUSIC = 33;    
  { PAL   }
    TITLE_PAL = 34;    
  { SAMP  }
    WELCOME_SPL = 35;    

