
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


  { Allegro datafile object indexes, produced by grabber v4.4.2, Unix  }
  { Datafile: /home/guillermo/prog/bibliotecas/allegro-pas/allegro.pas.TRUNK/demo/demo.dat  }
  { Date: Mon Dec 10 19:21:11 2012  }
  { Do not hand edit!  }
  { BMP   }

  const
    BMP_COIN = 0;    
  { BMP   }
    BMP_BLK1 = 1;    
  { BMP   }
    BMP_BLK2 = 2;    
  { BMP   }
    BMP_BLK3 = 3;    
  { BMP   }
    BMP_ROW_R = 4;    
  { BMP   }
    BMP_ROW_L = 5;    
  { BMP   }
    BMP_ROW_D = 6;    
  { RLE   }
    BMP_BOMB1 = 7;    
  { RLE   }
    BMP_BOMB2 = 8;    
  { RLE   }
    BMP_EXPLOSION1 = 9;    
  { RLE   }
    BMP_EXPLOSION2 = 10;    
  { RLE   }
    BMP_MAIN_L0 = 11;    
  { RLE   }
    BMP_MAIN_L1 = 12;    
  { RLE   }
    BMP_MAIN_L2 = 13;    
  { RLE   }
    BMP_MAIN_L3 = 14;    
  { RLE   }
    BMP_MAIN_LD = 15;    
  { RLE   }
    BMP_MAIN_LJ = 16;    
  { RLE   }
    BMP_MAIN_R0 = 17;    
  { RLE   }
    BMP_MAIN_R1 = 18;    
  { RLE   }
    BMP_MAIN_R2 = 19;    
  { RLE   }
    BMP_MAIN_R3 = 20;    
  { RLE   }
    BMP_MAIN_RD = 21;    
  { RLE   }
    BMP_MAIN_RJ = 22;    
  { FONT  }
    GAME_FONT = 23;    
  { SAMP  }
    GAME_MUSIC = 24;    
  { PAL   }
    GAME_PAL = 25;    
  { FLIC  }
    INTRO_ANIM = 26;    
  { MIDI  }
    INTRO_MUSIC = 27;    
  { SAMP  }
    INTRO_SPL = 28;    
  { SAMP  }
    SND_COIN = 29;    
  { SAMP  }
    SND_DEAD = 30;    
  { SAMP  }
    SND_EXPLODE = 31;    
  { SAMP  }
    SND_JUMP = 32;    
  { SAMP  }
    SND_WIN = 33;    
  { BMP   }
    TITLE_BMP = 34;    
  { FONT  }
    TITLE_FONT = 35;    
  { MIDI  }
    TITLE_MUSIC = 36;    
  { PAL   }
    TITLE_PAL = 37;    
  { SAMP  }
    WELCOME_SPL = 38;    

