
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


  { Allegro datafile object indexes, produced by grabber v4.4.2, Unix  }
  { Datafile: /home/guillermo/prog/bibliotecas/allegro-pas/allegro.pas.TRUNK/demo/demo.dat  }
  { Date: Wed Nov 28 14:05:57 2012  }
  { Do not hand edit!  }
  { BMP   }

  const
    BMP_START = 0;    
  { BMP   }
    BMP_END = 1;    
  { BMP   }
    BMP_COIN = 2;    
  { BMP   }
    BMP_BLK1 = 3;    
  { BMP   }
    BMP_BLK2 = 4;    
  { BMP   }
    BMP_BLK3 = 5;    
  { RLE   }
    BMP_BOMB1 = 6;    
  { RLE   }
    BMP_BOMB2 = 7;    
  { RLE   }
    BMP_EXPLOSION1 = 8;    
  { RLE   }
    BMP_EXPLOSION2 = 9;    
  { RLE   }
    BMP_MAIN_L0 = 10;    
  { RLE   }
    BMP_MAIN_L1 = 11;    
  { RLE   }
    BMP_MAIN_L2 = 12;    
  { RLE   }
    BMP_MAIN_L3 = 13;    
  { RLE   }
    BMP_MAIN_LD = 14;    
  { RLE   }
    BMP_MAIN_LJ = 15;    
  { RLE   }
    BMP_MAIN_R0 = 16;    
  { RLE   }
    BMP_MAIN_R1 = 17;    
  { RLE   }
    BMP_MAIN_R2 = 18;    
  { RLE   }
    BMP_MAIN_R3 = 19;    
  { RLE   }
    BMP_MAIN_RD = 20;    
  { RLE   }
    BMP_MAIN_RJ = 21;    
  { FONT  }
    GAME_FONT = 22;    
  { SAMP  }
    GAME_MUSIC = 23;    
  { PAL   }
    GAME_PAL = 24;    
  { FLIC  }
    INTRO_ANIM = 25;    
  { MIDI  }
    INTRO_MUSIC = 26;    
  { SAMP  }
    INTRO_SPL = 27;    
  { SAMP  }
    SND_COIN = 28;    
  { SAMP  }
    SND_DEAD = 29;    
  { SAMP  }
    SND_EXPLODE = 30;    
  { SAMP  }
    SND_JUMP = 31;    
  { SAMP  }
    SND_WIN = 32;    
  { BMP   }
    TITLE_BMP = 33;    
  { FONT  }
    TITLE_FONT = 34;    
  { MIDI  }
    TITLE_MUSIC = 35;    
  { PAL   }
    TITLE_PAL = 36;    
  { SAMP  }
    WELCOME_SPL = 37;    

