
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


  { Allegro datafile object indexes, produced by grabber v4.4.2, Unix  }
  { Datafile: /home/guillermo/prog/bibliotecas/allegro-pas/allegro.pas.TRUNK/demo/mapedit.dat  }
  { Date: Wed Dec  5 18:53:56 2012  }
  { Do not hand edit!  }
  { BMP   }

  const
    BMP_1x1 = 0;    
  { BMP   }
    BMP_1X2 = 1;    
  { BMP   }
    BMP_2x1 = 2;    
  { BMP   }
    BMP_2X2 = 3;    
  { BMP   }
    BMP_DELETE = 4;    
  { BMP   }
    BMP_END = 5;    
  { BMP   }
    BMP_O_1X2 = 6;    
  { BMP   }
    BMP_O_2X1 = 7;    
  { BMP   }
    BMP_O_2X2 = 8;    
  { BMP   }
    BMP_START = 9;    

