# Makefile generic - Sources

#
# Builds the list of source files and object files for each bynary type.
#

# Lib files.
TEMP = $(wildcard $(LIBDIR)*.pas)
ifeq ($(strip $(TEMP)),)
$(error ERROR: No source code found at $(LIBDIR))
endif
LIBFILES = $(addprefix $(LIBDIR),$(addsuffix .pas, $(basename $(notdir $(TEMP) ) ) ) )

# For the examples.
TEM2 = $(wildcard $(EXMDIR)*.pp)
ifeq ($(strip $(TEM2)),)
$(error ERROR: No source code found at $(EXMDIR))
endif
EXMFILES = $(addprefix $(EXMBIN),$(addsuffix $(BINSUF), $(basename $(notdir $(TEM2) ) ) ) )

# For the demo game.
TEM3 = $(wildcard $(ALEXDIR)*.pas)
ifeq ($(strip $(TEM3)),)
$(error ERROR: No source code found at $(ALEXDIR))
endif
TEM4 = $(wildcard $(ALEXDIR)*.pp)
ifeq ($(strip $(TEM4)),)
$(error ERROR: No source code found at $(ALEXDIR))
endif
ALEXSRC = $(ALEXDIR)%.pp $(TEM3)
ALEXDEMO = $(addprefix $(ALEXBIN),$(addsuffix $(BINSUF), $(basename $(notdir $(TEM4) ) ) ) )
