
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


  { Allegro datafile object indexes, produced by grabber v4.4.1, Unix  }
  { Datafile: /home/guillermo/prog/bibliotecas/allegro-pas/demo/demo.dat  }
  { Date: Sun Sep 19 16:17:14 2010  }
  { Do not hand edit!  }
  { BMP   }

  const
     BMP_START = 0;
  { BMP   }
     BMP_END = 1;
  { BMP   }
     BMP_COIN = 2;
  { BMP   }
     BMP_BLK1 = 3;
  { BMP   }
     BMP_BLK2 = 4;
  { BMP   }
     BMP_BLK3 = 5;
  { RLE   }
     BMP_BOMB1 = 6;
  { RLE   }
     BMP_BOMB2 = 7;
  { RLE   }
     BMP_EXPLOSION1 = 8;
  { RLE   }
     BMP_EXPLOSION2 = 9;
  { RLE   }
     BMP_MAIN_L0 = 10;
  { RLE   }
     BMP_MAIN_L1 = 11;
  { RLE   }
     BMP_MAIN_L2 = 12;
  { RLE   }
     BMP_MAIN_LD = 13;
  { RLE   }
     BMP_MAIN_LJ = 14;
  { RLE   }
     BMP_MAIN_R0 = 15;
  { RLE   }
     BMP_MAIN_R1 = 16;
  { RLE   }
     BMP_MAIN_R2 = 17;
  { RLE   }
     BMP_MAIN_RD = 18;
  { RLE   }
     BMP_MAIN_RJ = 19;
  { FONT  }
     GAME_FONT = 20;
  { SAMP  }
     GAME_MUSIC = 21;
  { PAL   }
     GAME_PAL = 22;
  { FLIC  }
     INTRO_ANIM = 23;
  { MIDI  }
     INTRO_MUSIC = 24;
  { SAMP  }
     INTRO_SPL = 25;
  { SAMP  }
     SND_COIN = 26;
  { SAMP  }
     SND_DEAD = 27;
  { SAMP  }
     SND_EXPLODE = 28;
  { SAMP  }
     SND_JUMP = 29;
  { SAMP  }
     SND_WIN = 30;
  { BMP   }
     TITLE_BMP = 31;
  { FONT  }
     TITLE_FONT = 32;
  { MIDI  }
     TITLE_MUSIC = 33;
  { PAL   }
     TITLE_PAL = 34;
  { SAMP  }
     WELCOME_SPL = 35;

