# Makefile generic - Sources

#
# Builds the list of source files and object files for each bynary type.
#

# Lib files.
TEMP = $(wildcard $(LIBDIR)*.pas)
ifeq ($(strip $(TEMP)),)
$(error ERROR: No source code found at $(LIBDIR))
endif
LIBFILES = $(addprefix $(LIBDIR),$(addsuffix .pas, $(basename $(notdir $(TEMP) ) ) ) )

# For the examples.
TEM2 = $(wildcard $(EXMDIR)*.pp)
ifeq ($(strip $(TEM2)),)
$(error ERROR: No source code found at $(EXMDIR))
endif
EXMFILES = $(addprefix $(EXMDIR),$(addsuffix $(BINSUF), $(basename $(notdir $(TEM2) ) ) ) )

#TEM5 = $(wildcard $(EXMDIR)agl/*.pp)
#ifeq ($(strip $(TEM5)),)
#$(error ERROR: No source code found at $(EXMDIR)agl/)
#endif
#GLEXMFILES += $(addprefix $(EXMDIR)agl/,$(addsuffix $(BINSUF), $(basename $(notdir $(TEM5) ) ) ) )

GLEXMFILES = $(EXMDIR)agl/exbasic$(BINSUF)

# For the demo game.
TEM3 = $(wildcard $(DEMODIR)*.pas)
ifeq ($(strip $(TEM3)),)
$(error ERROR: No source code found at $(DEMODIR))
endif
TEM4 = $(wildcard $(DEMODIR)*.pp)
ifeq ($(strip $(TEM4)),)
$(error ERROR: No source code found at $(DEMODIR))
endif
DEMOSRC = $(DEMODIR)%.pp $(TEM3)
DEMO = $(addprefix $(DEMODIR),$(addsuffix $(BINSUF), $(basename $(notdir $(TEM4) ) ) ) )


# For the tools.
TSETUPSRC = $(TOOLDIR)setup/setup.pp $(TOOLDIR)setup/DoSetup.pas $(TOOLDIR)setup/SimpleGUI.pas
TGRABBSRC = $(TOOLDIR)grabber/grabber.pp $(TOOLDIR)grabber/main.pas
