
{$IFDEF FPC}
{$PACKRECORDS C}
{$ENDIF}


  { Allegro datafile object indexes, produced by grabber v4.2.1, MinGW32  }
  { Datafile: e:\trabajo\prog\allegro.pas\demo\demo.dat  }
  { Date: Sun Oct 21 21:14:08 2007  }
  { Do not hand edit!  }
  { BMP   }

  const
     BMP_BLK1 = 0;
  { BMP   }
     BMP_BLK2 = 1;
  { BMP   }
     BMP_BLK3 = 2;
  { RLE   }
     BMP_BOMB1 = 3;
  { RLE   }
     BMP_BOMB2 = 4;
  { RLE   }
     BMP_COIN = 5;
  { RLE   }
     BMP_END = 6;
  { RLE   }
     BMP_EXPLOSION1 = 7;
  { RLE   }
     BMP_EXPLOSION2 = 8;
  { RLE   }
     BMP_MAIN_L0 = 9;
  { RLE   }
     BMP_MAIN_L1 = 10;
  { RLE   }
     BMP_MAIN_L2 = 11;
  { RLE   }
     BMP_MAIN_LD = 12;
  { RLE   }
     BMP_MAIN_LJ = 13;
  { RLE   }
     BMP_MAIN_R0 = 14;
  { RLE   }
     BMP_MAIN_R1 = 15;
  { RLE   }
     BMP_MAIN_R2 = 16;
  { RLE   }
     BMP_MAIN_RD = 17;
  { RLE   }
     BMP_MAIN_RJ = 18;
  { FONT  }
     GAME_FONT = 19;
  { SAMP  }
     GAME_MUSIC = 20;
  { PAL   }
     GAME_PAL = 21;
  { FLIC  }
     INTRO_ANIM = 22;
  { MIDI  }
     INTRO_MUSIC = 23;
  { SAMP  }
     INTRO_SPL = 24;
  { SAMP  }
     SND_COIN = 25;
  { SAMP  }
     SND_DEAD = 26;
  { SAMP  }
     SND_EXPLODE = 27;
  { SAMP  }
     SND_JUMP = 28;
  { SAMP  }
     SND_WIN = 29;
  { BMP   }
     TITLE_BMP = 30;
  { FONT  }
     TITLE_FONT = 31;
  { MIDI  }
     TITLE_MUSIC = 32;
  { PAL   }
     TITLE_PAL = 33;
  { SAMP  }
     WELCOME_SPL = 34;

